### ISSUE TITLE
Install a font

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm-edu#1]
It's not a big deal, but I didn't manage to install a font properly. 

I am running this postbuild:

https://github.com/OGGM/oggm-edu/blob/0e5729fbc458ed476e87048e976b3e1f5418c136/postBuild#L5-L8

But the build errors with:

```
Fontconfig error: Cannot load default config file
```

@TimoRoth if ever you happen to know what to do I'd be interested - not very important though.

**Comment by fmaussion** [comment]
To debug the Docker builds we could do this locally: https://github.com/jupyter/repo2docker 

(but it's really not the most important issue ;-)

**Comment by nchampollion** [comment]
I know it was just to warm up a little bit ! However, it's solved in my laptop ... maybe someone else should test it.

**Comment by fmaussion** [comment]
Yes, locally it works - the issue is about installing a font on a docker container so that binder can use it. 

To be honest I think only @TimoRoth can solve this ;-)

**Comment by nchampollion** [comment]
I see ! Indeed, we need rescue from @TimoRoth :-)

**Comment by fmaussion** [comment]
This now works nicely ;-) 

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/OGGM/oggm-edu/master?filepath=gen_plots%2Fela_changes_response_time.ipynb)
