### ISSUE TITLE
Remove baseline images 

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm-edu#134]
@Holmgren825 I've been a bit quick in merging haha

I really appreciate the effort to use baseline images for the tests, but I'd rather not have them. They are a real pain to maintain, and one day you will be gone and it will fall back to me ;-) 

Furthermore, it will make many things painful to change, since each change to the plot will also change the tests, etc.

Tests are good, but here I really think we should keep tests as slick and simple as possible.

**Comment by Holmgren825** [comment]
Ok, understand! Will fix.
