### ISSUE TITLE
Adding api reference to docs

### ISSUE THREAD

**Issue by Holmgren825** [OGGM/oggm-edu#140]
It is probably a good idea to add a reference of the full API to the docs. Even though notebooks cover most of the functionality, it is a bit tedious to use them as reference. Not sure how much work this would be, but it would raise the quality even more I believe.

**Comment by fmaussion** [comment]
Yes. Its actually relatively little work if your classes are well documented.

**Comment by fmaussion** [comment]
As a first step you just need to add an API page to the oggm-edu sphinx page like OGGM

**Comment by Holmgren825** [comment]
Nice, I will investigate.

**Comment by fmaussion** [comment]
Sphinx will parse the python files, so what you need to do is document the classes properly (see e.g. the GlacierDirectory class in OGGM) and sphinx displays it:

- https://github.com/OGGM/oggm/blob/a0c8857a3420fb652b93039ce0a28ebe2b996c19/oggm/utils/_workflow.py#L2353
- https://docs.oggm.org/en/latest/generated/oggm.GlacierDirectory.html
