### ISSUE TITLE
Check that the notebook still work after the API changes from the doc PR

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm-edu#145]
@Holmgren825 can you check that https://github.com/OGGM/oggm-edu/pull/142 did not introduce bugs in the notebooks? 

Also revert _current_state to be public not private maybe

**Comment by Holmgren825** [comment]
The notebooks work! Regarding ``_current_state``, my reasoning behind this being private now is that it is not intended to be used by the user. ``state_history``  have anything the user could want from ``_current_state`` I think, in a nicer packaging.

**Comment by Holmgren825** [comment]
Well, I guess the same plot could be made by using the ``state_history``. All plotting methods were written before we used ``oggm.run_until_and_store``, when the flowline that is stored in ``_current_state`` was the only thing we knew about the glacier geometry.

``_current_state`` is still convenient to use to get the latest glacier geometry, for plots etc. What I meant with that it is not useful for the user is that the flowline object isn't straightforward to interact with. I guess "private" more refers to that it should only be used inside the parent class, and not to discourage users from using it. I can revert it back to being public.

**Comment by fmaussion** [comment]
> I can revert it back to being public.

I think its fine to make it public and say in the doc: "For advanced users: get access to the OGGM flowline object"

**Comment by Holmgren825** [comment]
Sounds good!
