### ISSUE TITLE
Who are the "future improvements" sections for?

### ISSUE THREAD

**Issue by ehultee** [OGGM/oggm-edu#163]
On the Glacier Gallery page, "Future Improvements" encourages readers to contribute glacier info and describes how.  On the World Glacier Explorer page, the "Future Improvements" header reads a bit more like notes to the team of what could be tackled next--like a GitHub issue that isn't in the repo.  None of the other pages on the site have these "Future Improvements" sections.  

Do you want to clarify the purpose and audience of these sections?

**Comment by fmaussion** [comment]
Thanks! I think we should delete and move the discussion to the respective repositories.

edu.oggm.org should just provide a link to the repositories and say that development is happening there

**Comment by fmaussion** [comment]
Addressed in https://github.com/OGGM/oggm-edu/pull/169
