### ISSUE TITLE
Add name attribute to 'Glacier' and 'GlacierCollection' objects

### ISSUE THREAD

**Issue by ehultee** [OGGM/oggm-edu#187]
After last year's updates, the workflow to make an experiment (like the [simple bed slope comparison](https://github.com/ehultee/glaciology-labs/blob/main/1_glacier_bed_slope-2022.ipynb) that can be compared with goo) has changed.  

Students modifying the new workflow noticed that it would be helpful to add a 'Name' attribute to `Glacier` and `GlacierCollection` objects.  This would help with bookkeeping when there are several idealized glaciers that the students are supposed to compare with one another.

**Comment by Holmgren825** [comment]
Hey Lizz!
This sounds like a good addition. I can take a look at it. Spontaneously I'm thinking of adding it as an optional argument which by default assigns a random id to the glacier if no name is provided.

**Comment by ehultee** [comment]
Sounds great.  Thank you Erik!

**Comment by fmaussion** [comment]
I've commented on the PR. I think it needs a bit more thinking as to what to do "per default", because the new default IDs will be quite unintuitive.
