### ISSUE TITLE
New documentation & notebooks !

### ISSUE THREAD

**Issue by nchampollion** [OGGM/oggm-edu#32]
I'm a little bit confused. If I want to create a new notebook, what should I do ? Putting into oggm-edu or oggm ? Using .rst or .ipynb files ? Putting in docs, notebooks, gen_plots, run_examples or experiments directory ? Link with the list of notebooks ? I think I understand some things but it's not super clear. A readme in the oggm-edu and oggm directories could be helpful. Or maybe adding these information into `contributing.rst` file ...

**Comment by fmaussion** [comment]
>  Or maybe adding these information into `contributing.rst` file ...

Good idea! 

the place for notebooks is now OGGM Edu!
