### ISSUE TITLE
World glaciers explorer does not work

### ISSUE THREAD

**Issue by zschirmeister** [OGGM/oggm-edu#66]
Some people told me that the interactive app: World glacier explorer does not appear. There is only a grey page.
Here the link from the oggm-edu webpage: https://dash.klima.uni-bremen.de/bokeh/app
I tried it also from different devices, maybe the link is wrong?

**Comment by TimoRoth** [comment]
The link is correct, and the app also claims to be loading, and all its source is there in the Browser.
Just something, somewhere, with bokeh broke, and it's not actually starting to render anything.

I looked at it for quite a while last week, and couldn't figure out what's wrong. All logs I have claim success.
