### ISSUE TITLE
Long term concept for the bokeh apps

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm-edu#67]
We currently have a dash server (https://github.com/pyviz-demos/glaciers) which is not linked anywhere but can continue to run as a "legacy" app.

We have one single bokeh app, which doesn't work currently: https://dash.klima.uni-bremen.de/bokeh/app . The code of this app is, as far as I know, not hosted on github. @TimoRoth made a script out of the notebook I wrote in https://github.com/OGGM/bokeh-apps and is serving it somewhere (a VM in Bremen?).

It looks like we are going to move towards the Bokeh/Holoviz/Panel ecosystem altogether (Patrick started to develop a new app already). We are going to have at least three apps by the end of the year, so we need a system to serve these apps (and update them) without too much burden for @TimoRoth and all involved.

The optimal way for me would be a model like panel does: https://panel.pyviz.org/ . Each app has a given url: e.g. https://gapminder.pyviz.demo.anaconda.com/app, https://glaciers.pyviz.demo.anaconda.com, etc., and each app has a github repository: https://github.com/pyviz-demos/ 

This way, we have the server, and a possible fallback would be to run the apps on mybinder as well if the server doesn't work (e.g. the binder link om [glaciers](https://github.com/pyviz-demos/glaciers)).

@TimoRoth - I know it was a bit of a mess to serve the current app, and also to debug the "white screen" issue. Do you thing that it would make sense to reach out to the panel devs to ask for their set-up? They are very responsive in general!

**Comment by TimoRoth** [comment]
The bokeh App is pretty much the unmodified notebook from the pyviz demo, just converted to a regular python script so I can host it: https://github.com/TimoRoth/glaciers

**Comment by fmaussion** [comment]
I'm quite confident it's possible to serve notebooks as well - in all cases, we will have to centralize the apps under OGGM org, either as scripts or notebooks.
